### ISSUE TITLE
Misleading exception

### ISSUE THREAD

**Issue by PeterWalchhofer** [ccs-amsterdam/amcat4py#8]
When I upload a document to amcat4 via amcat4py and forget  the required fields (title, text, date) the following exception is being raised

```
Unexpected exception formatting exception. Falling back to standard exception
Traceback (most recent call last):
  File "/home/peter/anaconda3/envs/vds/lib/python3.10/site-packages/amcat4py/amcatclient.py", line 84, in _request
    r.raise_for_status()
  File "/home/peter/anaconda3/envs/vds/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: http://localhost/amcat/index/speeches_aut/documents

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/peter/anaconda3/envs/vds/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_31037/2743098145.py", line 1, in <module>
    amcat.upload_documents("speeches_aut", speeches_aut.to_dicts())
  File "/home/peter/anaconda3/envs/vds/lib/python3.10/site-packages/amcat4py/amcatclient.py", line 267, in upload_documents
    self._post("documents", index=index, json=body)
  File "/home/peter/anaconda3/envs/vds/lib/python3.10/site-packages/amcat4py/amcatclient.py", line 100, in _post
    return self._request("post", url=self._url(url, index), data=data, headers=headers, ignore_status=ignore_status)
  File "/home/peter/anaconda3/envs/vds/lib/python3.10/site-packages/amcat4py/amcatclient.py", line 86, in _request
    raise AmcatError(e.response, e.request) from e
amcat4py.amcatclient.AmcatError: Error from server (422): [{'loc': ['body', 'documents', 0, 'title']
[...]
'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'documents', 98, 'title'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'documents', 99, 'title'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['body', 'documents', 100, 'title'], 'msg': 'field required', 'type': 'value_error.missing'}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/peter/anaconda3/envs/vds/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 2052, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "/home/peter/anaconda3/envs/vds/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1118, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/peter/anaconda3/envs/vds/lib/python3.10/site-packages/IPython/core/ultratb.py", line 1012, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/peter/anaconda3/envs/vds/lib/python3.10/site-packages/IPython/core/ultratb.py", line 865, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/home/peter/anaconda3/envs/vds/lib/python3.10/site-packages/IPython/core/ultratb.py", line 818, in format_exception_as_a_whole
    frames.append(self.format_record(r))
  File "/home/peter/anaconda3/envs/vds/lib/python3.10/site-packages/IPython/core/ultratb.py", line 736, in format_record
    result += ''.join(_format_traceback_lines(frame_info.lines, Colors, self.has_colors, lvals))
  File "/home/peter/anaconda3/envs/vds/lib/python3.10/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/peter/anaconda3/envs/vds/lib/python3.10/site-packages/stack_data/core.py", line 734, in lines
    pieces = self.included_pieces
  File "/home/peter/anaconda3/envs/vds/lib/python3.10/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/peter/anaconda3/envs/vds/lib/python3.10/site-packages/stack_data/core.py", line 677, in included_pieces
    scope_pieces = self.scope_pieces
  File "/home/peter/anaconda3/envs/vds/lib/python3.10/site-packages/stack_data/utils.py", line 144, in cached_property_wrapper
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/peter/anaconda3/envs/vds/lib/python3.10/site-packages/stack_data/core.py", line 614, in scope_pieces
    scope_start, scope_end = self.source.line_range(self.scope)
  File "/home/peter/anaconda3/envs/vds/lib/python3.10/site-packages/stack_data/core.py", line 178, in line_range
    return line_range(self.asttext(), node)
  File "/home/peter/anaconda3/envs/vds/lib/python3.10/site-packages/executing/executing.py", line 428, in asttext
    self._asttext = ASTText(self.text, tree=self.tree, filename=self.filename)
  File "/home/peter/anaconda3/envs/vds/lib/python3.10/site-packages/asttokens/asttokens.py", line 307, in __init__
    super(ASTText, self).__init__(source_text, filename)
  File "/home/peter/anaconda3/envs/vds/lib/python3.10/site-packages/asttokens/asttokens.py", line 44, in __init__
    source_text = six.ensure_text(source_text)
AttributeError: module 'six' has no attribute 'ensure_text'
```
The client seems not to handle 422 error or forward the server's error msg

This differs from `amcat4r`, which prints `The fields title, date, and text are required and can never be NA`

**Comment by vanatteveldt** [comment]
Thanks for the bug report!

Could you provide a minimal example of python code that triggers this exception? That would make it a lot easier to debug.

**Comment by PeterWalchhofer** [comment]
I just tried it again, but after restarting my jupyter kernel I was unable to reproduce it. Sorry for that!
It seems like that I polluted my python env by  accidently installing amcat4client instead of amcat4py at the beginning...

However, another thing that I noticed is that, when uploading documents with an index-identifier that does not exist, a HTTP 500  error code is being returned without a message: `amcat4py.amcatclient.AmcatError: Error from server (500): Internal Server Error`

steps to reproduce:
```
amcat.upload_documents("does_not_exist", [valid_doc])
```
